### ISSUE TITLE
Is it possible to startup this project locally?

### ISSUE THREAD

**Issue by culpgrant** [dagster-io/dagster-open-platform#2]
I was wondering if anyone has been able to get the project working locally. Thank you!

**Comment by PedramNavid** [comment]
Hi @culpgrant, it is not! This is only a subset of our internal pipeline and is intended to show people what real Dagster data pipeline code looks like, but will not work outside of our own environment as it depends on environment variables, custom resources, and some other code we have decided to not share.

**Comment by culpgrant** [comment]
Thank you makes sense!
